# Generated by Django 3.0.8 on 2020-07-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jinto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jinto',
        ),
    ]
