# Generated by Django 3.0.6 on 2020-05-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proneapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Question',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='option',
            name='op1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='option',
            name='op2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='option',
            name='op3',
            field=models.CharField(max_length=100),
        ),
    ]
